## scripts/build_draft_manuscript_v1.R
## Assembles the draft-manuscript candidate figures (rebuilt at
## consistent journal-ready specifications — see SESSION_LOG.md 2026-06-30)
## into review/figures/draft_manuscript_v1/ under descriptive filenames,
## alongside a matching .legend.txt for each. As of 2026-10-02 (figure stage
## 2: Figure 1 map/cumulative site-years moved out -- see "Fig 1 note"
## below; Figure 5 removed -- see "Fig 5 note" below) this script itself
## copies only figures 2 and 3; Figure 1 (map), its cumulative site-years
## companion, and Figure 4 and its Extended Data companion are all copied
## directly by their own generating scripts (see the "Fig 1 note" and
## "Fig 4 note" below).
##
## This is a pure file-copy utility (no flux data read, no credentials) —
## it intentionally does not call check_pipeline_config(). Source figures
## must already exist; run the relevant generate_*.R / figure_*.R script
## first if a source is missing or stale.
##
## Fig 1 note (figure stage 2, 2026-10-02): the map becomes its own
## main-text figure. draft_manuscript_v1/fig_map_network.png/.pdf (the five
## panels formerly in the Extended Data supp_map_regional: Equal Earth world
## overview + four Lambert Azimuthal Equal-Area regional panels, 183 mm
## wide) is built and written directly by scripts/generate_fig_map_network.R,
## NOT by this script -- the same pattern as the Fig 4 note below. Cumulative
## site-years by IGBP is now its OWN standalone main-text figure (no panel
## letter), draft_manuscript_v1/fig_cumulative_siteyears_igbp.png/.pdf, built
## directly by scripts/generate_fig_cumulative_siteyears.R, also absent from
## the copy map below. The three files these two scripts replace --
## fig_01.*, fig_01a_map_current_network.*, fig_01b_cumulative_siteyears_
## igbp.* -- were retired to draft_manuscript_v1/deprecated/, and the
## Extended Data source they also replace, SupFigs/supp_map_regional.*, was
## retired to SupFigs/deprecated/ (both not regenerated by this script). See
## SESSION_LOG.md 2026-10-02, figure stage 2.
##
## Fig 1B note (superseded by the Fig 1 note above, 2026-10-02): this script
## previously performed the fig_dur11_CumulativeSiteYears_IGBP.png ->
## fig_01b_cumulative_siteyears_igbp.png copy/rename itself, since Dur11 has
## no script that writes it directly under an "fig_01b_*" name.
## scripts/generate_fig_cumulative_siteyears.R now calls the same
## fig_cumulative_siteyears_igbp() panel-building function directly (without
## panel_letter()) and writes its own output under the new name, so no
## copy/rename step is needed any more; scripts/generate_duration_
## histograms.R is unaffected and still writes Dur11 under its own canonical
## name in review/figures/network/.
##
## Fig 4 note: as of 2026-10-02, Figure 4 (fig_04_representativeness.png,
## Geo vs Data) and its Extended Data companion (supp_representativeness_
## geo_vs_geo.png, Geo vs Geo -- Nature takes no Supplementary Information
## figures, so this is Extended Data, not a "supplemental figure") are built
## and copied directly by scripts/figure4_representativeness.R, not by this
## build script -- the former into review/figures/draft_manuscript_v1/, the
## latter into review/figures/draft_manuscript_v1/SupFigs/ -- so both are
## absent from the figs/legends maps below. The previous
## Figure 4 (fig_04_current_network_sampling_ratios.png, sourced here from
## fig_rep001_current.png) is superseded; its output and legend were moved
## to review/figures/draft_manuscript_v1/deprecated/ (not regenerated by
## this script). See SESSION_LOG.md 2026-10-02.
##
## Fig 2 note: as of 2026-08-31, Figure 2's source is
## review/figures/candidates/ALT_fig_02_whittaker_current.png — promoted
## from candidate status (see SESSION_LOG.md 2026-08-31, "ALT_fig_02
## promoted to draft Figure 2"). Same network hexbin + 95% solid / 99%
## dashed global ice-free-land HDR contour overlay as the prior source
## (review/figures/whittaker/fig_whit_fig2_with_both_contours.png, built by
## scripts/generate_whittaker_overlays.R), built instead by
## scripts/generate_whittaker_alt_fig02_update.R via fig_whittaker_worldclim()
## with hex_regular = TRUE (previously-elongated hexagons now regular) and
## points_in_front = TRUE (previously grey points behind the hexbins, now a
## quiet dark charcoal, half-size, drawn on top), a pale-tan NEE
## colour-scale centre (was near-white; blue/red endpoints unchanged), and a
## corrected/tightened inset (the previous "N = <n> sites | <n> site-years"
## line conflated the full network count with a separately NEE-filtered
## count — see SESSION_LOG.md 2026-08-31, "775 vs 638 sites"). The prior
## source and its build output are preserved at
## review/figures/draft_manuscript_v1/deprecated/. Its legend is NOT copied
## from the source figure's own .txt (that file uses the candidates/
## folder's plain-caption convention, not this manuscript legend's format,
## and separately never carried the retired Mahalanobis coverage statistic
## in the first place) — it is instead hardcoded below so the swap
## reproduces deterministically.
##
## Fig 5 note: as of 2026-10-02, Figure 5 (fig_05_jaccard_trajectory_with_
## counts.png, sourced from fig_rep008_jaccard_trajectory_with_counts.png)
## is taken out of the draft manuscript -- removed from the figs/legends
## maps below and no longer copied by this script. Its prior output and
## legend were moved to review/figures/draft_manuscript_v1/deprecated/ (not
## regenerated by this script). See SESSION_LOG.md 2026-10-02.

library(fs)
library(jsonlite)

out_dir <- file.path("review", "figures", "draft_manuscript_v1")
fs::dir_create(out_dir)

# ---- Figure copy map ---------------------------------------------------------
# source PNG -> descriptive draft-manuscript filename
figs <- list(
  list(src = "review/figures/candidates/ALT_fig_02_whittaker_current.png",
       dst = "fig_03_whittaker_current.png"),
  list(src = "review/figures/flux_medians/fig_flux_comparison_combo_nep_et_h.png",
       dst = "fig_04_flux_comparison_combo_nep_et_h.png")
  # Figure 1 map (fig_map_network.png) and the standalone cumulative
  # site-years figure (fig_cumulative_siteyears_igbp.png) are no longer
  # sourced here -- see "Fig 1 note" above.
  # Figure 4 (fig_04_representativeness.png) is no longer sourced here --
  # see "Fig 4 note" above.
  # Figure 5 (fig_05_jaccard_trajectory_with_counts.png) is no longer
  # sourced here -- see "Fig 5 note" above.
)

for (f in figs) {
  if (!file.exists(f$src)) {
    stop("Source figure not found: ", f$src,
         " — run its generate_*.R / figure_*.R script first.")
  }
  dst_path <- file.path(out_dir, f$dst)
  file.copy(f$src, dst_path, overwrite = TRUE)
  message("Copied: ", f$src, " -> ", dst_path)

  # A PDF beside every PNG (Nature format rule, 2026-10-02): if the source
  # has a sibling PDF at the same stem, copy it too under the matching
  # draft-manuscript stem. Not all sources have one yet (candidate figures
  # not yet re-rendered to the Nature format) -- a missing PDF is reported,
  # not a stop(), so partial re-renders don't block the whole build.
  src_pdf <- sub("\\.png$", ".pdf", f$src)
  if (file.exists(src_pdf)) {
    dst_pdf <- sub("\\.png$", ".pdf", dst_path)
    file.copy(src_pdf, dst_pdf, overwrite = TRUE)
    message("Copied: ", src_pdf, " -> ", dst_pdf)
  } else {
    message("  (no sibling PDF at ", src_pdf, " -- not yet re-rendered to the Nature format)")
  }
}

# ---- Legend copy map ---------------------------------------------------------
# source .legend.txt -> descriptive draft-manuscript legend filename
# Fig 4/5 legends already existed (Rep008/Rep001) and are copied verbatim
# except for a corrected DIMENSIONS line reflecting this session's resize.
# Fig 4 and Fig 5 were swapped 2026-07-01 to match the manuscript section
# order (sampling ratios now precedes the Jaccard trajectory) — see
# SESSION_LOG.md 2026-07-01.
# Fig 2's legend is NOT in this copy map — see the "Fig 2 note" above and the
# hardcoded block below.
legends <- list(
  list(src = "review/figures/flux_medians/fig_flux_comparison_combo_nep_et_h.legend.txt",
       dst = "fig_04_flux_comparison_combo_nep_et_h.legend.txt",
       fix_dims = NULL, fig_number = 4)
  # Figure 1 map / cumulative site-years legends are no longer sourced here
  # -- see "Fig 1 note" above.
  # Figure 4's legend (fig_04_representativeness.legend.txt) is no longer
  # sourced here -- see "Fig 4 note" above.
  # Figure 5's legend (fig_05_jaccard_trajectory_with_counts.legend.txt) is
  # no longer sourced here -- see "Fig 5 note" above.
)

for (l in legends) {
  if (!file.exists(l$src)) {
    stop("Source legend not found: ", l$src)
  }
  dst_path <- file.path(out_dir, l$dst)
  txt <- readLines(l$src)
  if (!is.null(l$fix_dims)) {
    txt <- sub("^DIMENSIONS:.*$", l$fix_dims, txt)
  }
  # Figure stage 6 (2026-10-02): the draft-manuscript copy's own filename and
  # figure number differ from the source legend's self-description (the
  # source file keeps its own canonical, unnumbered name per docs/
  # figure_inventory.md) -- rewrite the "FIGURE LEGEND --" header line to
  # this copy's own filename, and prefix TITLE with the manuscript figure
  # number, without touching the source file.
  dst_png_name <- sub("\\.legend\\.txt$", ".png", l$dst)
  txt <- sub("^FIGURE LEGEND .*$", paste0("FIGURE LEGEND — ", dst_png_name), txt)
  if (!is.null(l$fig_number)) {
    txt <- sub("^TITLE: ", paste0("TITLE: Figure ", l$fig_number, ". "), txt)
  }
  writeLines(txt, dst_path)
  message("Copied: ", l$src, " -> ", dst_path)
}

# ---- Fig 2 legend: hardcoded (base layer + contour overlay, no coverage stat) ----
# ALT_fig_02_whittaker_current.txt (the source figure's own caption, written
# by scripts/generate_whittaker_alt_fig02_update.R) uses the candidates/
# folder's plain-caption convention, not this manuscript legend's format, so
# is NOT copied here (same as the pre-promotion source). This block writes
# the manuscript legend directly so it reproduces deterministically; keep
# this text in sync by hand if the base layer or overlay method changes
# materially. Updated 2026-08-31 for the ALT_fig_02 promotion -- see
# SESSION_LOG.md 2026-08-31, "ALT_fig_02 promoted to draft Figure 2".
# Fig 2 site counts are read from the counts sidecar written by
# scripts/generate_whittaker_alt_fig02_update.R (n_sites/n_nee_sites/
# n_site_years/snapshot_file, computed at that script's run time from the
# pinned snapshot + R/site_annual_fluxes.R::compute_site_annual_fluxes(),
# revised 2026-10-02 from the DuckDB annual_converted table) rather than hand-typed,
# so the legend text cannot silently drift from what the figure actually
# plots -- see SESSION_LOG.md 2026-09-01, "Fix hardcoded Fig 2 legend site
# count". The sidecar is required; this script stops rather than falling
# back to a stale hardcoded count if it is missing.
fig02_counts_path <- "review/figures/candidates/ALT_fig_02_whittaker_current.counts.json"
if (!file.exists(fig02_counts_path)) {
  stop("Fig 2 counts sidecar not found: ", fig02_counts_path,
       " — run scripts/generate_whittaker_alt_fig02_update.R first.")
}
fig02_counts <- jsonlite::fromJSON(fig02_counts_path)

fig02_legend <- c(
  "FIGURE LEGEND — fig_03_whittaker_current.png",
  "==============================================",
  "",
  "TITLE: Figure 3. Whittaker climate-space distribution of the current FLUXNET network,",
  "coloured by median annual net ecosystem exchange, with global ice-free-land",
  "climate-space contours overlaid",
  "",
  "DESCRIPTION:",
  "Two layers on one panel.",
  "",
  paste0("BASE LAYER: hexagonal-binned scatter plot placing every current FLUXNET"),
  paste0("Shuttle site (N = ", fig02_counts$n_sites,
         " sites) in Whittaker climate space — mean annual"),
  "temperature (MAT, WorldClim v2.1 BIO1) by mean annual precipitation (MAP,",
  "BIO12). Each hexagonal bin is coloured by the median, across the towers",
  "falling in that climate-space bin, of each tower's own median annual net",
  "ecosystem exchange (median of site medians -- see BINNING, below) --",
  "values from R/site_annual_fluxes.R::compute_site_annual_fluxes() (see DATA",
  "SOURCES). A hexagon with no towers is white (not drawn -- there is no",
  "neutral/background fill colour on this panel, so white and \"no data\" are",
  "the same thing). Hexagons are regular (equilateral) by construction",
  "(fig_whittaker_worldclim(..., hex_regular = TRUE) -- binwidth computed",
  "explicitly from the axis limits and coord_fixed() pins the MAT:MAP",
  "physical-length ratio; the previous no-hex_regular figure used in earlier",
  "drafts rendered hexagons visibly elongated on the vertical/MAP axis, a",
  "rendering artefact of ggplot2::stat_summary_hex()'s default bin sizing,",
  "not a data issue). Individual site locations are additionally overplotted",
  "as small, low-opacity dark charcoal points, drawn in front of the",
  "hexagons (points_in_front = TRUE), so sampling density within each",
  "hexagon reads as fine texture without obscuring the flux colour beneath.",
  "Points are shown for ALL network sites regardless of NEE availability —",
  "only the hexbin colouring is restricted to sites with qualifying NEE (see",
  "inset, below). An inset in the upper-left reports three counts, computed",
  "at figure-build time from the data (not hardcoded): the full network site",
  "count, the count of those sites with at least one qualifying annual NEE",
  "value, and the resulting site-year count.",
  "",
  "OVERLAY: two contour lines mark the 95% (solid) and 99% (dashed)",
  "highest-density regions (HDR) of the area-weighted distribution of global",
  "ice-free land in the same MAT/MAP space — i.e. where global land area is",
  "concentrated in climate space, independent of the FLUXNET network. The",
  "density surface is computed from WorldClim v2.1 BIO1/BIO12 over an ESA",
  "CCI land-cover 2015 ice-free-land mask (water bodies and permanent",
  "snow/ice excluded, plus a latitude backstop for Antarctica), area-weighted",
  "by the cosine of latitude (WorldClim is an equal-angle, not equal-area,",
  "grid), via a weighted 2D kernel density estimate over the full, unclipped",
  "global distribution. The 95% contour marks the climates where most global",
  "land area sits; the 99% contour extends further out to include rarer",
  "climatic extremes. The two lines are distinguished by line type only",
  "(both black) and are identified in this legend rather than by an",
  "in-panel label or key — no contour text or legend box is drawn on the",
  "figure itself.",
  "",
  "A small fraction of global land area (1.18%) falls in climates outside",
  "the displayed axis ranges (MAT below -15 or above 35 degC; MAP above",
  "4000 mm/yr) and is not shown, on either layer.",
  "",
  "AXES:",
  "  X — Mean Annual Temperature (°C), fixed range -15 to 35",
  "  Y — Mean Annual Precipitation (mm yr⁻¹), fixed range 0 to 4000",
  "",
  "Four-sided black tick marks (inward) are drawn on all axes via a",
  "duplicated secondary axis with no labels. Panel has a solid black border",
  "and no gridlines.",
  "",
  "COLOUR SCALE (base layer only — the overlay has no fill/colour; revised",
  "2026-10-02, task 3):",
  "Stepped ColorBrewer RdBu scale, 8 classes, no middle/neutral class -- the",
  "bin edge at NEE = 0 is a hard sink/source boundary, not a neutral bin.",
  "5 sink (blue) steps covering NEE <= 0, each 100 g C m⁻² yr⁻¹ wide",
  "except the open-ended lowest: below -400, -400 to -300, -300 to -200,",
  "-200 to -100, -100 to 0. 3 source (red/orange) steps covering NEE > 0,",
  "same 100 g C m⁻² yr⁻¹ step width, open-ended at the top: 0 to 100,",
  "100 to 200, above 200. Colours, most negative to most positive: #053061,",
  "#2166AC, #4393C3, #92C5DE, #D1E5F0 (sink), #FDDBC7, #F4A582, #D6604D",
  "(source). A hexagon whose median falls beyond -400 or beyond 200 takes",
  "the corresponding open-ended step's colour (\"below -400\"/\"above 200\") --",
  "there is no separate out-of-range/clip colour. Step width (100) and the",
  "two end points (-400, 200) are named constants (NEE_STEP_WIDTH,",
  "NEE_SINK_END, NEE_SOURCE_END) in scripts/generate_whittaker_alt_fig02_",
  "update.R. Implemented via new fig_whittaker_worldclim() parameters",
  "fill_mode = \"stepped\", step_breaks, step_colours (default fill_mode =",
  "\"continuous\", unchanged, for every other caller).",
  "",
  "BINNING (base layer):",
  "Hexagonal binning via ggplot2::stat_summary_hex(), 15 bins along each",
  "axis; summary statistic per bin is the median of per-site median annual",
  "NEE values (median-of-medians), then discretised into the 8 steps above.",
  "90 hexagons are drawn in total: below -400 (16), -400 to -300 (8), -300 to",
  "-200 (14), -200 to -100 (16), -100 to 0 (26), 0 to 100 (7), 100 to 200",
  "(0 -- no hexagon's median fell in this step), above 200 (3). The lowest",
  "and highest hexagon medians (before discretising) are -1361.1 and 234.6",
  "g C m⁻² yr⁻¹.",
  "",
  "NETWORK AND SITE COUNT:",
  paste0("FLUXNET Shuttle network, current pinned snapshot: N = ", fig02_counts$n_sites),
  paste0("sites (", fig02_counts$n_nee_sites,
         " with a qualifying annual NEE value); inset text on the figure"),
  paste0("reports \"", fig02_counts$n_sites, " sites total\", \"",
         fig02_counts$n_nee_sites, " with annual NEE\", \"",
         fig02_counts$n_site_years, " site-years\"."),
  "",
  "DATA SOURCES:",
  paste0("  - Site list: ", fig02_counts$snapshot_file),
  paste0("    (", fig02_counts$n_sites, " sites)"),
  "  - Climate (MAT/MAP), both layers: WorldClim v2.1, 2.5 arc-minute BIO1",
  "    and BIO12; base layer uses the pre-extracted per-site table",
  "    data/snapshots/site_worldclim.csv (fallback: on-the-fly",
  "    terra::extract()); overlay uses the full global BIO1/BIO12 GeoTIFFs",
  "  - Land mask (overlay only): ESA CCI land cover 2015",
  "    (ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7.tif)",
  "  - Flux data (base layer only): R/site_annual_fluxes.R::",
  "    compute_site_annual_fluxes() (revised 2026-10-02), DuckDB `annual`",
  "    table (data/duckdb/fluxnet.duckdb), FLUXMET dataset, gated per-site on",
  "    QC_THRESHOLD_YY via the scripts/04_qc.R VUT/CUT rule -- a site's",
  "    plotted value is the median of its qualifying annual NEE values",
  "",
  "EXCLUSIONS (base layer):",
  "Two independent reasons a tower can be missing from the hexbin summary",
  "(but never from the overlaid points -- see BASE LAYER, above):",
  "  - No WorldClim climate match: the tower's coordinates returned no MAT/MAP",
  "    value from site_worldclim.csv (the primary source) or, for sites not in",
  "    that table, from an on-the-fly terra::extract() against the WorldClim",
  "    GeoTIFFs -- i.e. the tower cannot be placed in MAT/MAP space at all, so",
  "    it is absent from the whole panel, not merely unfilled on the colour",
  "    scale. 0 of 781 current-network towers are affected (checked directly",
  "    against site_worldclim.csv at figure-build time).",
  "  - No qualifying annual NEE value: the tower has a climate-space position",
  "    but no QC_THRESHOLD_YY-qualifying annual NEE value, so its own median",
  "    cannot contribute to any hexagon's colour; it still appears as a point.",
  "No IGBP or other classification filter is applied.",
  "",
  "REPRODUCIBILITY:",
  "Base layer function: fig_whittaker_worldclim() in R/figures/fig_climate.R",
  "  (hex_regular = TRUE, points_in_front = TRUE, point_colour = \"#2B2B2B\",",
  "  point_size = 0.35, point_alpha = 0.35, fill_mode = \"stepped\",",
  "  step_breaks = seq(-400, 200, by = 100), step_colours = <see COLOUR SCALE",
  "  above>, detail_lines = <the three counts above>, detail_hjust = 0,",
  "  detail_x_offset = 0.6)",
  "Overlay functions:   fig_whittaker_global_contour(),",
  "                     build_global_landclimate(), .weighted_density_grid(),",
  "                     .hdr_levels() in R/figures/fig_climate.R",
  "Source script:       scripts/generate_whittaker_alt_fig02_update.R",
  "Output:              review/figures/candidates/ALT_fig_02_whittaker_current.png/.pdf,",
  "                     copied to",
  "                     review/figures/draft_manuscript_v1/fig_03_whittaker_current.png/.pdf",
  "                     by scripts/build_draft_manuscript_v1.R",
  "DIMENSIONS:          89 x 89 mm, 600 dpi PNG + vector PDF, Helvetica, white",
  "                     background. All text 5-7pt (axis titles/text 7pt;",
  "                     step-legend labels 5pt; inset text ~5pt).",
  "Prior version:       review/figures/draft_manuscript_v1/deprecated/",
  "                     (moved 2026-08-31, not overwritten -- see",
  "                     SESSION_LOG.md and review/figures/RUN_LOG_fig02_promote.txt)",
  "DIMENSIONS: 3.5 × 3.5 inches, 300 dpi, white background"
)
fig02_legend_path <- file.path(out_dir, "fig_03_whittaker_current.legend.txt")
writeLines(fig02_legend, fig02_legend_path)
message("Wrote: ", fig02_legend_path, " (hardcoded, not copied)")

message("\nDone. draft_manuscript_v1/ contains ", length(figs), " figures and ",
        length(legends) + 1, " legends.")
