## promote_fig02_to_draft.R
## Orchestrates promoting the ALT Whittaker candidate to draft Figure 2:
##  1. Fix the inset block's left-axis clip (already applied to
##     R/figures/fig_climate.R and scripts/generate_whittaker_alt_fig02_update.R
##     before this script runs -- see the run log's parameter-check step,
##     which verifies rather than re-derives the fix) and regenerate
##     review/figures/candidates/ALT_fig_02_whittaker_current.png.
##  2. Move the current draft Figure 2 (PNG + legend) to
##     review/figures/draft_manuscript_v1/deprecated/, preserving filename
##     (no overwrite -- a date/version suffix is appended on collision).
##  3. Verify scripts/build_draft_manuscript_v1.R's Figure 2 source now
##     points at the ALT candidate (already edited before this script runs;
##     verified, not performed, here -- see the note on "Update
##     scripts/build_draft_manuscript_v1.R" below).
##  4. Re-run scripts/build_draft_manuscript_v1.R so
##     review/figures/draft_manuscript_v1/fig_02_whittaker_current.png (+
##     .legend.txt) reflect the new source.
##
## Note on "Update scripts/build_draft_manuscript_v1.R": the source-path
## and hardcoded-legend edits to that script are text/content changes made
## directly (via the same editing mechanism as every other code change this
## session), not generated by this orchestration script re-writing another
## script's source with string substitution -- regex-editing a sibling R
## script's source from within an R script is fragile and harder to review
## than a direct, verifiable edit. This script's job is strictly the
## promotion MECHANICS (regenerate, move, verify, rebuild), and it verifies
## (does not blindly trust) that the expected source-path edit landed before
## proceeding -- see the "verify build script Fig 2 source" step below,
## which stops rather than substitutes if the expected line is absent.
##
## Run-log discipline (this script's own most important instruction): a
## durable run log is created as the VERY FIRST action, before any other
## work, flushed after every write, with a line before and after every step
## -- each input/function located or found missing (with the exact path
## checked), each value computed, each file written. The whole pipeline
## runs inside a function called via tryCatch() so the final outcome line
## is written UNCONDITIONALLY -- on.exit() registered at Rscript top level
## does not fire on normal completion (the same pattern used throughout
## this session's other run-logged scripts). If a required input is
## missing, the missing item and the path checked are logged, the final
## outcome line is written, and the script stops -- no substitution.
##
## Output:
##   review/figures/RUN_LOG_fig02_promote.txt (this run's durable log)
##   review/figures/candidates/ALT_fig_02_whittaker_current.png (+.txt) -- regenerated with the
##     inset-clip fix
##   review/figures/draft_manuscript_v1/deprecated/fig_02_whittaker_current.png (+.legend.txt) --
##     the prior draft Figure 2, moved (not copied)
##   review/figures/draft_manuscript_v1/fig_02_whittaker_current.png (+.legend.txt) -- the new
##     promoted version, via re-running scripts/build_draft_manuscript_v1.R

run_log_path <- file.path("review", "figures", "RUN_LOG_fig02_promote.txt")

# ---- Run log: created as the VERY FIRST action, before any other work ----
if (!dir.exists(dirname(run_log_path))) dir.create(dirname(run_log_path), recursive = TRUE)
run_log_con <- file(run_log_path, open = "w")
rl <- function(...) {
  ts   <- format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
  line <- paste0(ts, " ", paste0(..., collapse = ""))
  cat(line, "\n", sep = "", file = run_log_con)
  flush(run_log_con)
  message(line)
}
rl("STARTED: promote_fig02_to_draft.R")

# Whole pipeline runs inside a function called via tryCatch() so the final
# outcome line is written unconditionally -- on.exit() registered at Rscript
# top level does not fire on normal completion (same pattern as
# scripts/generate_whittaker_overlays.R and scripts/generate_whittaker_
# alt_fig02_update.R earlier this session).
run_pipeline <- function() {

  # ---- Step: resolve which script actually builds the current ALT candidate ----
  rl("attempting: resolve the ALT-generating script. Task text named ",
     "scripts/generate_whittaker_alt_fig02.R; checking both that path and its ",
     "successor, scripts/generate_whittaker_alt_fig02_update.R (which is the one that ",
     "actually produced the current review/figures/candidates/ALT_fig_02_whittaker_current.png ",
     "-- confirmed via git log --oneline -1 on that PNG before this run: commit adf9890, ",
     "'Update ALT_fig_02: charcoal points, pale-tan NEE centre, tightened inset', authored by ",
     "scripts/generate_whittaker_alt_fig02_update.R, not the original script)")
  base_alt_path   <- "scripts/generate_whittaker_alt_fig02.R"
  update_alt_path <- "scripts/generate_whittaker_alt_fig02_update.R"
  if (!file.exists(base_alt_path)) {
    rl("MISSING: ", base_alt_path, " -- checked exact path '", base_alt_path, "'. (Not fatal --",
       " this path is the ORIGINAL base ALT script, superseded earlier this session; only",
       " logged for completeness.)")
  } else {
    rl("found: ", base_alt_path, " (original base ALT script -- superseded, not used below)")
  }
  if (!file.exists(update_alt_path)) {
    rl("MISSING REQUIRED INPUT: ", update_alt_path, " -- checked exact path '", update_alt_path,
       "'. This is the script that actually produces the current ALT candidate PNG; without it ",
       "there is nothing correct to promote. Not substituting -- stopping.")
    stop("Required file not found: ", update_alt_path, call. = FALSE)
  }
  rl("found: ", update_alt_path, " -- USING THIS SCRIPT (resolves the task-text/actual-state ",
     "discrepancy noted above)")
  alt_script <- update_alt_path

  # ---- Step: verify the inset-clip fix (detail_x_offset) is already in place -------
  rl("attempting: verify R/figures/fig_climate.R's fig_whittaker_worldclim() exposes ",
     "detail_x_offset (the new parameter fixing the inset block's left-axis clip)")
  if (!file.exists("R/figures/fig_climate.R")) {
    rl("MISSING REQUIRED INPUT: R/figures/fig_climate.R -- checked exact path ",
       "'R/figures/fig_climate.R'. Not substituting -- stopping.")
    stop("Required file not found: R/figures/fig_climate.R", call. = FALSE)
  }
  source("R/pipeline_config.R")
  source("R/plot_constants.R")
  source("R/figures/fig_climate.R")
  suppressMessages({ library(dplyr); library(ggplot2); library(fs) })
  if (!"detail_x_offset" %in% names(formals(fig_whittaker_worldclim))) {
    rl("MISSING REQUIRED FUNCTION PARAMETER: detail_x_offset -- checked ",
       "formals(fig_whittaker_worldclim). The inset-clip fix has not been applied. Not ",
       "substituting -- stopping.")
    stop("fig_whittaker_worldclim() is missing required parameter: detail_x_offset", call. = FALSE)
  }
  rl("found: fig_whittaker_worldclim() has detail_x_offset")
  fix_line <- grep("detail_x_offset_new", readLines(alt_script), value = TRUE)[1]
  if (is.na(fix_line)) {
    rl("MISSING: ", alt_script, " does not appear to set detail_x_offset_new -- checked via grep ",
       "on the script source. Not substituting -- stopping.")
    stop(alt_script, " does not set detail_x_offset_new.", call. = FALSE)
  }
  rl("found: ", alt_script, " sets detail_x_offset_new -- '", trimws(fix_line), "'")

  # ---- Step: regenerate the ALT candidate with the inset-clip fix ------------------
  rl("attempting: Rscript ", alt_script, " (regenerates review/figures/candidates/",
     "ALT_fig_02_whittaker_current.png with the inset-clip fix; its own run log, ",
     "review/figures/candidates/RUN_LOG_alt_fig02_update.txt, records every input/value/file for ",
     "that regeneration in full -- not duplicated here)")
  status <- system2("Rscript", shQuote(alt_script), stdout = TRUE, stderr = TRUE)
  exit_code <- attr(status, "status")
  if (!is.null(exit_code) && exit_code != 0L) {
    rl("ERROR: Rscript ", alt_script, " exited non-zero (", exit_code, "). Last lines of output: ",
       paste(tail(status, 5), collapse = " | "))
    stop("Rscript ", alt_script, " failed (exit ", exit_code, ").", call. = FALSE)
  }
  alt_png <- "review/figures/candidates/ALT_fig_02_whittaker_current.png"
  if (!file.exists(alt_png)) {
    rl("MISSING after regeneration: ", alt_png, " -- checked exact path '", alt_png,
       "' post-Rscript-run. Not substituting -- stopping.")
    stop("Expected output not found after regeneration: ", alt_png, call. = FALSE)
  }
  alt_info <- file.info(alt_png)
  rl("completed: ", alt_png, " regenerated (", alt_info$size, " bytes, mtime ",
     format(alt_info$mtime, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"), ")")

  # ---- Step: create draft_manuscript_v1/deprecated/ if missing ---------------------
  deprecated_dir <- file.path("review", "figures", "draft_manuscript_v1", "deprecated")
  rl("attempting: check for ", deprecated_dir)
  if (!dir.exists(deprecated_dir)) {
    dir.create(deprecated_dir, recursive = TRUE)
    rl("completed: created ", deprecated_dir, " (did not exist)")
  } else {
    rl("found: ", deprecated_dir, " (already existed)")
  }

  # ---- Step: move the current draft Figure 2 (PNG + legend) into deprecated/ -------
  draft_dir  <- file.path("review", "figures", "draft_manuscript_v1")
  old_png    <- file.path(draft_dir, "fig_02_whittaker_current.png")
  old_legend <- file.path(draft_dir, "fig_02_whittaker_current.legend.txt")

  move_with_collision_check <- function(src_path, label) {
    rl("attempting: locate current draft ", label, " at ", src_path)
    if (!file.exists(src_path)) {
      rl("MISSING REQUIRED INPUT: ", src_path, " -- checked exact path '", src_path,
         "'. Not substituting -- stopping.")
      stop("Required file not found: ", src_path, call. = FALSE)
    }
    rl("found: ", src_path)
    dest_path <- file.path(deprecated_dir, basename(src_path))
    if (file.exists(dest_path)) {
      suffix    <- format(Sys.time(), "%Y%m%dT%H%M%S")
      ext       <- tools::file_ext(dest_path)
      stem      <- tools::file_path_sans_ext(dest_path)
      dest_path <- paste0(stem, "_", suffix, ".", ext)
      rl("decision: ", file.path(deprecated_dir, basename(src_path)), " already exists in ",
         deprecated_dir, " -- NOT overwriting. Appending a timestamp suffix instead: using ",
         dest_path)
    } else {
      rl("decision: no collision at ", dest_path, " -- preserving filename as-is")
    }
    ok <- file.rename(src_path, dest_path)
    if (!ok) {
      rl("ERROR: file.rename(", src_path, ", ", dest_path, ") returned FALSE")
      stop("Failed to move ", src_path, " to ", dest_path, call. = FALSE)
    }
    rl("completed: moved ", src_path, " -> ", dest_path)
    dest_path
  }

  moved_png    <- move_with_collision_check(old_png, "Figure 2 PNG")
  moved_legend <- move_with_collision_check(old_legend, "Figure 2 legend")

  # ---- Step: verify build_draft_manuscript_v1.R's Fig 2 source was updated ---------
  build_script <- "scripts/build_draft_manuscript_v1.R"
  rl("attempting: verify ", build_script, "'s Figure 2 source path (edited before this script ",
     "ran -- verifying, not performing, that edit; see the script header note on why)")
  if (!file.exists(build_script)) {
    rl("MISSING REQUIRED INPUT: ", build_script, " -- checked exact path '", build_script,
       "'. Not substituting -- stopping.")
    stop("Required file not found: ", build_script, call. = FALSE)
  }
  build_lines    <- readLines(build_script)
  old_src_line   <- grep('src = "review/figures/whittaker/fig_whit_fig2_with_both_contours.png"',
                          build_lines, value = TRUE, fixed = TRUE)
  new_src_line   <- grep('src = "review/figures/candidates/ALT_fig_02_whittaker_current.png"',
                          build_lines, value = TRUE, fixed = TRUE)
  # Also recover the OLD line verbatim from the last commit, for an exact before/after report
  # (the working copy alone only shows the NEW line, since the edit already happened).
  old_src_line_git <- tryCatch({
    prior <- system2("git", c("show", paste0("HEAD:", build_script)), stdout = TRUE, stderr = TRUE)
    grep('src = "review/figures/whittaker/fig_whit_fig2_with_both_contours.png"',
         prior, value = TRUE, fixed = TRUE)
  }, error = function(e) character(0))
  if (length(new_src_line) == 0L) {
    rl("MISSING: expected new Figure 2 source line ",
       '(src = "review/figures/candidates/ALT_fig_02_whittaker_current.png") not found in ',
       build_script, " -- checked via grep on the script source. The pre-condition edit this ",
       "script depends on has not been applied. Not substituting -- stopping.")
    stop(build_script, " does not have the expected new Figure 2 source line.", call. = FALSE)
  }
  rl("found: ", build_script, " already has the new Figure 2 source line")
  rl("SOURCE-PATH CHANGE (verbatim) -- OLD: ",
     if (length(old_src_line_git) > 0L) trimws(old_src_line_git[1]) else "(not recovered from git HEAD)",
     " | NEW: ", trimws(new_src_line[1]))

  # ---- Step: re-run the draft-manuscript build ---------------------------------------
  rl("attempting: Rscript ", build_script, " (rebuilds review/figures/draft_manuscript_v1/ from ",
     "the updated source map, including the new Figure 2 source)")
  build_status <- system2("Rscript", shQuote(build_script), stdout = TRUE, stderr = TRUE)
  build_exit   <- attr(build_status, "status")
  if (!is.null(build_exit) && build_exit != 0L) {
    rl("ERROR: Rscript ", build_script, " exited non-zero (", build_exit, "). Last lines of output: ",
       paste(tail(build_status, 10), collapse = " | "))
    stop("Rscript ", build_script, " failed (exit ", build_exit, ").", call. = FALSE)
  }
  rl("completed: Rscript ", build_script, " ran successfully (", length(build_status),
     " lines of output, not duplicated here)")

  # ---- Step: verify the new draft Figure 2 is in place and matches the ALT candidate ----
  new_png <- file.path(draft_dir, "fig_02_whittaker_current.png")
  rl("attempting: verify ", new_png, " exists post-rebuild and matches the regenerated ALT candidate")
  if (!file.exists(new_png)) {
    rl("MISSING after rebuild: ", new_png, " -- checked exact path '", new_png,
       "'. Not substituting -- stopping.")
    stop("Expected output not found after rebuild: ", new_png, call. = FALSE)
  }
  new_md5 <- tools::md5sum(new_png)
  alt_md5 <- tools::md5sum(alt_png)
  if (unname(new_md5) != unname(alt_md5)) {
    rl("WARNING: ", new_png, " (md5 ", unname(new_md5), ") does NOT match ", alt_png,
       " (md5 ", unname(alt_md5), ") -- unexpected given build_draft_manuscript_v1.R performs a ",
       "plain file.copy(); investigate before treating the promotion as complete.")
  } else {
    rl("completed: ", new_png, " matches ", alt_png, " byte-for-byte (md5 ", unname(new_md5), ")")
  }
  new_legend <- file.path(draft_dir, "fig_02_whittaker_current.legend.txt")
  if (!file.exists(new_legend)) {
    rl("MISSING after rebuild: ", new_legend, " -- checked exact path '", new_legend,
       "'. Not substituting -- stopping.")
    stop("Expected output not found after rebuild: ", new_legend, call. = FALSE)
  }
  rl("completed: ", new_legend, " present post-rebuild")

  rl("summary: moved ", moved_png, " and ", moved_legend, " (prior draft Figure 2, preserved); ",
     "promoted ", alt_png, " to ", new_png, " (+ ", new_legend, ") via ", build_script)

  invisible(TRUE)
}

pipeline_error <- tryCatch({
  run_pipeline()
  NULL
}, error = function(e) e)

if (is.null(pipeline_error)) {
  rl("outcome: SUCCESS -- ALT_fig_02_whittaker_current.png regenerated with the inset-clip fix, ",
     "prior draft Figure 2 moved to review/figures/draft_manuscript_v1/deprecated/, and ",
     "review/figures/draft_manuscript_v1/fig_02_whittaker_current.png (+.legend.txt) promoted.")
  message("\nDone: see ", run_log_path, " for the full trace.")
} else {
  rl("ERROR: ", conditionMessage(pipeline_error))
  rl("outcome: FAILED -- see the last 'attempting'/'MISSING' line above for what was in progress ",
     "when the script stopped.")
}
close(run_log_con)
if (!is.null(pipeline_error)) stop(pipeline_error)
